### ISSUE TITLE
Exercise duration being saved as 0 or less than 0

### ISSUE THREAD

**Issue by cascav4l** [EzerIT/BibleOL#18] opened 2023-10-25 16:26 UTC
When taking an exam, some students' exercise duration seems to be saving as a value that is less than or equal to 0. This then results in a divide by 0 error when trying to calculated the features per minute.

**Comment by oliverglanz** [comment] 2023-10-26 01:47
This error is not exam related! It appears with exercises as well. It seems to result from a bug in the original BibleOL code that is responsible for recording exercises. To give an example:

This quiz was taken by students: https://learner.bible/text/show_quiz?quiz=Andrews%20University%2FJAM_Test%2FHebrew-02_01_SDATS_Vocabulary%20midterm.3et&count=10

When the instructor goes to MY DATA/Students' performance/ and then selects that particular exercise to show the graphs it shows this:

<img width="592" alt="image" src="https://github.com/EzerIT/BibleOL/assets/8409738/71c869ae-b6be-4075-96d1-b803759d1aca">

When this error mesage appears here (under Students' performance) it will also create error messages for the grading module and the exam module as those modules rely on the same data storing code that "Students' performances relies on. To demonstrate this: When you go to "Grade Quizzes" and select that particular exercise from above you get the same error message:

<img width="602" alt="image" src="https://github.com/EzerIT/BibleOL/assets/8409738/601e674f-e4db-4f43-8f11-56719470a7b1">


THis in turn will create the same error message when that exercise was part of an exam and the DivisionByZeroError occured.

**Comment by oliverglanz** [comment] 2023-10-26 11:53
Here is a short screen recording that shows the issue: https://drive.google.com/file/d/1Fwn_smnEhO0TLwGRVnjpDhATlb0LjwMK/view?usp=sharing

**Comment by tmccormack165** [comment] 2023-11-07 14:37
This issue was resolved in:
[Set minimum exercise duration to 1 second](https://github.com/EzerIT/BibleOL/commit/dd5815885d0e21a88a308ad35c0e5162534c1d62) and [Fix the division by zero issues](https://github.com/EzerIT/BibleOL/commit/053ef1b7cda309faad337cab1b359efee8f8f12f)

The root cause was solved by setting a minimum duration for all exercises within an exam.

**Closed by tmccormack165** 2023-11-07 14:37 UTC

**Comment by mabioc** [comment] 2023-11-07 14:43
Thank you Tim.
